name: Deploying to DEV server
on: [push, pull_request]

# since jobs run in parallel and steps run sequentially
# 1 job, many steps
# 1) SSH into remote server
# 2) Update codebase via git pull
# 3) Build docker images
# 4) Start the kubernetes cluster using helm

# all jobs run in parallel by default
jobs:
  deploy_to_DO:
    name: Deploying to DO
    runs-on: ubuntu-latest
    steps:
        - name: SSH into DEV server
          env:
          run: |
            echo "SSH-ing into server"

        - name: Updaing codebase
          env:
          run: |
            echo "Update codebase using git-pull"

        - name: Building Docker images
          env:
          run: |
            echo "Building docker images for service"

        - name: Starting kubernetes cluster
          env:
          run: |
            echo "Staring K8s cluster using some Helm command"