# this is where we declare our workflow

# workflow will be executed when the `push` event is triggered
name: A workflow for my Hello World file
on: push

# jobs run actions as steps
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
